local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

google:
  service: GCS
  project: Friendo
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: dog-photo-bucket

google_dev:
  service: GCS
  project: Friendo
  credentials: <%= Rails.root.join("config/secrets/dog-photos.json") %>
  bucket: dog-photo-bucket